package com.bmp.constant;

public enum CamplainStatus {
	
	NEW,ASSIGNED,WORKING,PARTIAL_WORKING,IN_PROGRESS,AWAITING_YOUR_REPLY,ON_HOLD,RESOLVED,CLOSED
	
	/* NEW,ASSIGNED,WORKING,PARTIAL_WORKING,NOT_ATTEMPT,CLOSED */
}
