package com.bmp.constant;

public enum CashQueryName {
	READY_FOR_DRS, INTRANSIT_DRS, INTERNAL_TRANSFER_FWD, THREEPL_TRANSFER, DATA_RECEIVED,
	INCOMING_MANIFEST, PENDING_BAG_FOR_DEBAG, PENDING_BAG_FOR_MANIFEST, NEW_PICKUP_REQUEST,
	DRS_POD_COUNT, PICKUP_POD_COUNT, INTRANSIT_PICKUP_SHEET,PENDING_FOR_INSCAN, 
	RTO_INITIATED, RTO_GENERATED_PACKETS, MISSING_PACKETS, C2C_ORDERS, 
	MANIFEST_GENERATED_SHIPMENTS, BAG_GENERATED_PACKETS, DRS_GENERATED_PACKETS, THREEPL_GENERATED_PACKETS,
	INTERNAL_TRANSFER_RTO_PACKETS, PARTNER_PENDENCY, PICK_SHEET_GENERATED_PACKETS, PENDING_3PL_MANIFEST_POD,
	SOFDATA_NOT_RECIVED, REATTEMPT_SHIPMENT_DRS, PACKET_ON_HOLD, COD_AWAITED_BRANCH_END,
	AWAITING_CLIENT_INSTRUCTION, ORDER_VERIFIED_PENDING_FOR_SCANNING
	
}