package com.bmp.constant;

public enum LogTypes {
	ORDER_PUSH,STATUS_UPDATE,STATUS_PUSH,SMS,MAIL,APP_NOTIFICATION,WAREHOUSE_PUSH,WAREHOUSE_UPDATE,PICKUP_REQUEST,
	CANCEL_PICKUP_REQUEST,GET_PRINT_LABEL,GET_PRINT_LR_LABEL,GET_WAYBILL_SERIES,B2C_NDR_REQUEST,LR_REQUEST
}
