//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.14 at 07:34:30 PM IST 
//


package com.bmp.model.app.api.jaxbean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reqcnt" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="details">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="res">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="DOCKET_NO" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="ORDER_NO" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="errmsg">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="err" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "result",
    "reqcnt",
    "details"
})
@XmlRootElement(name = "response")
public class GatiPickupResponse {

    @XmlElement(required = true)
    protected String result;
    protected byte reqcnt;
    @XmlElement(required = true)
    protected GatiPickupResponse.Details details;

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResult(String value) {
        this.result = value;
    }

    /**
     * Gets the value of the reqcnt property.
     * 
     */
    public byte getReqcnt() {
        return reqcnt;
    }

    /**
     * Sets the value of the reqcnt property.
     * 
     */
    public void setReqcnt(byte value) {
        this.reqcnt = value;
    }

    /**
     * Gets the value of the details property.
     * 
     * @return
     *     possible object is
     *     {@link GatiPickupResponse.Details }
     *     
     */
    public GatiPickupResponse.Details getDetails() {
        return details;
    }

    /**
     * Sets the value of the details property.
     * 
     * @param value
     *     allowed object is
     *     {@link GatiPickupResponse.Details }
     *     
     */
    public void setDetails(GatiPickupResponse.Details value) {
        this.details = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="res">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="DOCKET_NO" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="ORDER_NO" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="errmsg">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="err" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "res"
    })
    public static class Details {

        @XmlElement(required = true)
        protected GatiPickupResponse.Details.Res res;

        /**
         * Gets the value of the res property.
         * 
         * @return
         *     possible object is
         *     {@link GatiPickupResponse.Details.Res }
         *     
         */
        public GatiPickupResponse.Details.Res getRes() {
            return res;
        }

        /**
         * Sets the value of the res property.
         * 
         * @param value
         *     allowed object is
         *     {@link GatiPickupResponse.Details.Res }
         *     
         */
        public void setRes(GatiPickupResponse.Details.Res value) {
            this.res = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="DOCKET_NO" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="ORDER_NO" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="errmsg">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="err" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "docketno",
            "orderno",
            "errmsg"
        })
        public static class Res {

            @XmlElement(name = "DOCKET_NO")
            protected int docketno;
            @XmlElement(name = "ORDER_NO")
            protected long orderno;
            @XmlElement(required = true)
            protected GatiPickupResponse.Details.Res.Errmsg errmsg;

            /**
             * Gets the value of the docketno property.
             * 
             */
            public int getDOCKETNO() {
                return docketno;
            }

            /**
             * Sets the value of the docketno property.
             * 
             */
            public void setDOCKETNO(int value) {
                this.docketno = value;
            }

            /**
             * Gets the value of the orderno property.
             * 
             */
            public long getORDERNO() {
                return orderno;
            }

            /**
             * Sets the value of the orderno property.
             * 
             */
            public void setORDERNO(long value) {
                this.orderno = value;
            }

            /**
             * Gets the value of the errmsg property.
             * 
             * @return
             *     possible object is
             *     {@link GatiPickupResponse.Details.Res.Errmsg }
             *     
             */
            public GatiPickupResponse.Details.Res.Errmsg getErrmsg() {
                return errmsg;
            }

            /**
             * Sets the value of the errmsg property.
             * 
             * @param value
             *     allowed object is
             *     {@link GatiPickupResponse.Details.Res.Errmsg }
             *     
             */
            public void setErrmsg(GatiPickupResponse.Details.Res.Errmsg value) {
                this.errmsg = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="err" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "err"
            })
            public static class Errmsg {

                @XmlElement(required = true)
                protected String err;

                /**
                 * Gets the value of the err property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getErr() {
                    return err;
                }

                /**
                 * Sets the value of the err property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setErr(String value) {
                    this.err = value;
                }

            }

        }

    }

}
