//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.02 at 05:36:55 PM IST 
//


package com.bmp.model.app.api.jaxbean;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Pickuprequest" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Custcode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="details">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="req">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="DOCKET_NO" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="DELIVERY_STN" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="GOODS_CODE" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="DECL_CARGO_VAL" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="ACTUAL_WT" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="CHARGED_WT" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="SHIPPER_CODE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="ORDER_NO" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="COD_AMT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="COD_IN_FAVOUR_OF" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="RECEIVER_CODE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="RECEIVER_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="RECEIVER_ADD1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="RECEIVER_ADD2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="RECEIVER_ADD3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="RECEIVER_ADD4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="RECEIVER_CITY" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="RECEIVER_PHONE_NO" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="RECEIVER_EMAIL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="RECEIVER_PINCODE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="NO_OF_PKGS" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="FROM_PKG_NO" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="TO_PKG_NO" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="PKGDETAILS">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="PKG_INFO" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="PKG_NO" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="PKG_LN" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="PKG_BR" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="PKG_HT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="PKG_WT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="RECEIVER_MOBILE_NO" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="Cust_Date_Delivey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SPL_Instruction" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PROD_SERV_CODE" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="CUSTVEND_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="GOODS_DESC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ORDER_QUANTITY" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="SELLER_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SELLER_ADD1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SELLER_ADD2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SELLER_ADD3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SELLER_DIST" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SELLER_CITY" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SELLER_PINCODE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="SELLER_STATE_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SELLER_PHONE_NO" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="SELLER_EMAIL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="BOOKING_BASIS" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="SELLER_TINNO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SELLER_VATNO" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="UOM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pickuprequest",
    "custcode",
    "details"
})
@XmlRootElement(name = "gati")
public class Gati {

    @XmlElement(name = "Pickuprequest", required = true)
    protected String pickuprequest;
    @XmlElement(name = "Custcode")
    protected int custcode;
    @XmlElement(required = true)
    protected Gati.Details details;

    /**
     * Gets the value of the pickuprequest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPickuprequest() {
        return pickuprequest;
    }

    /**
     * Sets the value of the pickuprequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPickuprequest(String value) {
        this.pickuprequest = value;
    }

    /**
     * Gets the value of the custcode property.
     * 
     */
    public int getCustcode() {
        return custcode;
    }

    /**
     * Sets the value of the custcode property.
     * 
     */
    public void setCustcode(int value) {
        this.custcode = value;
    }

    /**
     * Gets the value of the details property.
     * 
     * @return
     *     possible object is
     *     {@link Gati.Details }
     *     
     */
    public Gati.Details getDetails() {
        return details;
    }

    /**
     * Sets the value of the details property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gati.Details }
     *     
     */
    public void setDetails(Gati.Details value) {
        this.details = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="req">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="DOCKET_NO" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="DELIVERY_STN" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="GOODS_CODE" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="DECL_CARGO_VAL" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="ACTUAL_WT" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="CHARGED_WT" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="SHIPPER_CODE" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="ORDER_NO" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="COD_AMT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="COD_IN_FAVOUR_OF" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="RECEIVER_CODE" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="RECEIVER_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="RECEIVER_ADD1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="RECEIVER_ADD2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="RECEIVER_ADD3" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="RECEIVER_ADD4" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="RECEIVER_CITY" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="RECEIVER_PHONE_NO" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="RECEIVER_EMAIL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="RECEIVER_PINCODE" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="NO_OF_PKGS" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="FROM_PKG_NO" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="TO_PKG_NO" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="PKGDETAILS">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="PKG_INFO" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="PKG_NO" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                       &lt;element name="PKG_LN" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                       &lt;element name="PKG_BR" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                       &lt;element name="PKG_HT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                       &lt;element name="PKG_WT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="RECEIVER_MOBILE_NO" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="Cust_Date_Delivey" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SPL_Instruction" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PROD_SERV_CODE" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="CUSTVEND_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="GOODS_DESC" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ORDER_QUANTITY" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="SELLER_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SELLER_ADD1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SELLER_ADD2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SELLER_ADD3" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SELLER_DIST" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SELLER_CITY" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SELLER_PINCODE" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="SELLER_STATE_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SELLER_PHONE_NO" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="SELLER_EMAIL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="BOOKING_BASIS" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="SELLER_TINNO" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SELLER_VATNO" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="UOM" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "req"
    })
    public static class Details {

        @XmlElement(required = true)
        protected Gati.Details.Req req;

        /**
         * Gets the value of the req property.
         * 
         * @return
         *     possible object is
         *     {@link Gati.Details.Req }
         *     
         */
        public Gati.Details.Req getReq() {
            return req;
        }

        /**
         * Sets the value of the req property.
         * 
         * @param value
         *     allowed object is
         *     {@link Gati.Details.Req }
         *     
         */
        public void setReq(Gati.Details.Req value) {
            this.req = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="DOCKET_NO" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="DELIVERY_STN" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="GOODS_CODE" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="DECL_CARGO_VAL" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="ACTUAL_WT" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="CHARGED_WT" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="SHIPPER_CODE" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="ORDER_NO" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="COD_AMT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="COD_IN_FAVOUR_OF" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="RECEIVER_CODE" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="RECEIVER_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="RECEIVER_ADD1" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="RECEIVER_ADD2" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="RECEIVER_ADD3" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="RECEIVER_ADD4" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="RECEIVER_CITY" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="RECEIVER_PHONE_NO" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="RECEIVER_EMAIL" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="RECEIVER_PINCODE" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="NO_OF_PKGS" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="FROM_PKG_NO" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="TO_PKG_NO" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="PKGDETAILS">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="PKG_INFO" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="PKG_NO" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                             &lt;element name="PKG_LN" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="PKG_BR" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="PKG_HT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="PKG_WT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="RECEIVER_MOBILE_NO" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="Cust_Date_Delivey" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SPL_Instruction" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PROD_SERV_CODE" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="CUSTVEND_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="GOODS_DESC" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ORDER_QUANTITY" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="SELLER_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SELLER_ADD1" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SELLER_ADD2" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SELLER_ADD3" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SELLER_DIST" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SELLER_CITY" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SELLER_PINCODE" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="SELLER_STATE_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SELLER_PHONE_NO" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="SELLER_EMAIL" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="BOOKING_BASIS" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="SELLER_TINNO" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SELLER_VATNO" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="UOM" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "docketno",
            "deliverystn",
            "goodscode",
            "declcargoval",
            "actualwt",
            "chargedwt",
            "shippercode",
            "orderno",
            "codamt",
            "codinfavourof",
            "receivercode",
            "receivername",
            "receiveradd1",
            "receiveradd2",
            "receiveradd3",
            "receiveradd4",
            "receivercity",
            "receiverphoneno",
            "receiveremail",
            "receiverpincode",
            "noofpkgs",
            "frompkgno",
            "topkgno",
            "pkgdetails",
            "receivermobileno",
            "custDateDelivey",
            "splInstruction",
            "prodservcode",
            "custvendcode",
            "goodsdesc",
            "orderquantity",
            "sellername",
            "selleradd1",
            "selleradd2",
            "selleradd3",
            "sellerdist",
            "sellercity",
            "sellerpincode",
            "sellerstatecode",
            "sellerphoneno",
            "selleremail",
            "bookingbasis",
            "sellertinno",
            "sellervatno",
            "uom"
        })
        public static class Req {

            @XmlElement(name = "DOCKET_NO")
            protected int docketno;
            @XmlElement(name = "DELIVERY_STN")
            protected int deliverystn;
            @XmlElement(name = "GOODS_CODE")
            protected short goodscode;
            @XmlElement(name = "DECL_CARGO_VAL")
            protected short declcargoval;
            @XmlElement(name = "ACTUAL_WT")
            protected float actualwt;
            @XmlElement(name = "CHARGED_WT")
            protected float chargedwt;
            @XmlElement(name = "SHIPPER_CODE")
            protected int shippercode;
            @XmlElement(name = "ORDER_NO")
            protected long orderno;
            @XmlElement(name = "COD_AMT")
            protected byte codamt;
            @XmlElement(name = "COD_IN_FAVOUR_OF", required = true)
            protected String codinfavourof;
            @XmlElement(name = "RECEIVER_CODE")
            protected int receivercode;
            @XmlElement(name = "RECEIVER_NAME", required = true)
            protected String receivername;
            @XmlElement(name = "RECEIVER_ADD1", required = true)
            protected String receiveradd1;
            @XmlElement(name = "RECEIVER_ADD2", required = true)
            protected String receiveradd2;
            @XmlElement(name = "RECEIVER_ADD3", required = true)
            protected String receiveradd3;
            @XmlElement(name = "RECEIVER_ADD4", required = true)
            protected String receiveradd4;
            @XmlElement(name = "RECEIVER_CITY", required = true)
            protected String receivercity;
            @XmlElement(name = "RECEIVER_PHONE_NO")
            protected long receiverphoneno;
            @XmlElement(name = "RECEIVER_EMAIL", required = true)
            protected String receiveremail;
            @XmlElement(name = "RECEIVER_PINCODE")
            protected int receiverpincode;
            @XmlElement(name = "NO_OF_PKGS")
            protected byte noofpkgs;
            @XmlElement(name = "FROM_PKG_NO")
            protected int frompkgno;
            @XmlElement(name = "TO_PKG_NO")
            protected int topkgno;
            @XmlElement(name = "PKGDETAILS", required = true)
            protected Gati.Details.Req.PKGDETAILS pkgdetails;
            @XmlElement(name = "RECEIVER_MOBILE_NO")
            protected long receivermobileno;
            @XmlElement(name = "Cust_Date_Delivey", required = true)
            protected String custDateDelivey;
            @XmlElement(name = "SPL_Instruction", required = true)
            protected String splInstruction;
            @XmlElement(name = "PROD_SERV_CODE")
            protected byte prodservcode;
            @XmlElement(name = "CUSTVEND_CODE", required = true)
            protected String custvendcode;
            @XmlElement(name = "GOODS_DESC", required = true)
            protected String goodsdesc;
            @XmlElement(name = "ORDER_QUANTITY")
            protected byte orderquantity;
            @XmlElement(name = "SELLER_NAME", required = true)
            protected String sellername;
            @XmlElement(name = "SELLER_ADD1", required = true)
            protected String selleradd1;
            @XmlElement(name = "SELLER_ADD2", required = true)
            protected String selleradd2;
            @XmlElement(name = "SELLER_ADD3", required = true)
            protected String selleradd3;
            @XmlElement(name = "SELLER_DIST", required = true)
            protected String sellerdist;
            @XmlElement(name = "SELLER_CITY", required = true)
            protected String sellercity;
            @XmlElement(name = "SELLER_PINCODE")
            protected int sellerpincode;
            @XmlElement(name = "SELLER_STATE_CODE", required = true)
            protected String sellerstatecode;
            @XmlElement(name = "SELLER_PHONE_NO")
            protected long sellerphoneno;
            @XmlElement(name = "SELLER_EMAIL", required = true)
            protected String selleremail;
            @XmlElement(name = "BOOKING_BASIS")
            protected byte bookingbasis;
            @XmlElement(name = "SELLER_TINNO", required = true)
            protected String sellertinno;
            @XmlElement(name = "SELLER_VATNO")
            protected short sellervatno;
            @XmlElement(name = "UOM", required = true)
            protected String uom;

            /**
             * Gets the value of the docketno property.
             * 
             */
            public int getDOCKETNO() {
                return docketno;
            }

            /**
             * Sets the value of the docketno property.
             * 
             */
            public void setDOCKETNO(int value) {
                this.docketno = value;
            }

            /**
             * Gets the value of the deliverystn property.
             * 
             */
            public int getDELIVERYSTN() {
                return deliverystn;
            }

            /**
             * Sets the value of the deliverystn property.
             * 
             */
            public void setDELIVERYSTN(int value) {
                this.deliverystn = value;
            }

            /**
             * Gets the value of the goodscode property.
             * 
             */
            public short getGOODSCODE() {
                return goodscode;
            }

            /**
             * Sets the value of the goodscode property.
             * 
             */
            public void setGOODSCODE(short value) {
                this.goodscode = value;
            }

            /**
             * Gets the value of the declcargoval property.
             * 
             */
            public short getDECLCARGOVAL() {
                return declcargoval;
            }

            /**
             * Sets the value of the declcargoval property.
             * 
             */
            public void setDECLCARGOVAL(short value) {
                this.declcargoval = value;
            }

            /**
             * Gets the value of the actualwt property.
             * 
             */
            public float getACTUALWT() {
                return actualwt;
            }

            /**
             * Sets the value of the actualwt property.
             * 
             */
            public void setACTUALWT(float value) {
                this.actualwt = value;
            }

            /**
             * Gets the value of the chargedwt property.
             * 
             */
            public float getCHARGEDWT() {
                return chargedwt;
            }

            /**
             * Sets the value of the chargedwt property.
             * 
             */
            public void setCHARGEDWT(float value) {
                this.chargedwt = value;
            }

            /**
             * Gets the value of the shippercode property.
             * 
             */
            public int getSHIPPERCODE() {
                return shippercode;
            }

            /**
             * Sets the value of the shippercode property.
             * 
             */
            public void setSHIPPERCODE(int value) {
                this.shippercode = value;
            }

            /**
             * Gets the value of the orderno property.
             * 
             */
            public long getORDERNO() {
                return orderno;
            }

            /**
             * Sets the value of the orderno property.
             * 
             */
            public void setORDERNO(long value) {
                this.orderno = value;
            }

            /**
             * Gets the value of the codamt property.
             * 
             */
            public byte getCODAMT() {
                return codamt;
            }

            /**
             * Sets the value of the codamt property.
             * 
             */
            public void setCODAMT(byte value) {
                this.codamt = value;
            }

            /**
             * Gets the value of the codinfavourof property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCODINFAVOUROF() {
                return codinfavourof;
            }

            /**
             * Sets the value of the codinfavourof property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCODINFAVOUROF(String value) {
                this.codinfavourof = value;
            }

            /**
             * Gets the value of the receivercode property.
             * 
             */
            public int getRECEIVERCODE() {
                return receivercode;
            }

            /**
             * Sets the value of the receivercode property.
             * 
             */
            public void setRECEIVERCODE(int value) {
                this.receivercode = value;
            }

            /**
             * Gets the value of the receivername property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRECEIVERNAME() {
                return receivername;
            }

            /**
             * Sets the value of the receivername property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRECEIVERNAME(String value) {
                this.receivername = value;
            }

            /**
             * Gets the value of the receiveradd1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRECEIVERADD1() {
                return receiveradd1;
            }

            /**
             * Sets the value of the receiveradd1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRECEIVERADD1(String value) {
                this.receiveradd1 = value;
            }

            /**
             * Gets the value of the receiveradd2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRECEIVERADD2() {
                return receiveradd2;
            }

            /**
             * Sets the value of the receiveradd2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRECEIVERADD2(String value) {
                this.receiveradd2 = value;
            }

            /**
             * Gets the value of the receiveradd3 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRECEIVERADD3() {
                return receiveradd3;
            }

            /**
             * Sets the value of the receiveradd3 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRECEIVERADD3(String value) {
                this.receiveradd3 = value;
            }

            /**
             * Gets the value of the receiveradd4 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRECEIVERADD4() {
                return receiveradd4;
            }

            /**
             * Sets the value of the receiveradd4 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRECEIVERADD4(String value) {
                this.receiveradd4 = value;
            }

            /**
             * Gets the value of the receivercity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRECEIVERCITY() {
                return receivercity;
            }

            /**
             * Sets the value of the receivercity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRECEIVERCITY(String value) {
                this.receivercity = value;
            }

            /**
             * Gets the value of the receiverphoneno property.
             * 
             */
            public long getRECEIVERPHONENO() {
                return receiverphoneno;
            }

            /**
             * Sets the value of the receiverphoneno property.
             * 
             */
            public void setRECEIVERPHONENO(long value) {
                this.receiverphoneno = value;
            }

            /**
             * Gets the value of the receiveremail property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRECEIVEREMAIL() {
                return receiveremail;
            }

            /**
             * Sets the value of the receiveremail property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRECEIVEREMAIL(String value) {
                this.receiveremail = value;
            }

            /**
             * Gets the value of the receiverpincode property.
             * 
             */
            public int getRECEIVERPINCODE() {
                return receiverpincode;
            }

            /**
             * Sets the value of the receiverpincode property.
             * 
             */
            public void setRECEIVERPINCODE(int value) {
                this.receiverpincode = value;
            }

            /**
             * Gets the value of the noofpkgs property.
             * 
             */
            public byte getNOOFPKGS() {
                return noofpkgs;
            }

            /**
             * Sets the value of the noofpkgs property.
             * 
             */
            public void setNOOFPKGS(byte value) {
                this.noofpkgs = value;
            }

            /**
             * Gets the value of the frompkgno property.
             * 
             */
            public int getFROMPKGNO() {
                return frompkgno;
            }

            /**
             * Sets the value of the frompkgno property.
             * 
             */
            public void setFROMPKGNO(int value) {
                this.frompkgno = value;
            }

            /**
             * Gets the value of the topkgno property.
             * 
             */
            public int getTOPKGNO() {
                return topkgno;
            }

            /**
             * Sets the value of the topkgno property.
             * 
             */
            public void setTOPKGNO(int value) {
                this.topkgno = value;
            }

            /**
             * Gets the value of the pkgdetails property.
             * 
             * @return
             *     possible object is
             *     {@link Gati.Details.Req.PKGDETAILS }
             *     
             */
            public Gati.Details.Req.PKGDETAILS getPKGDETAILS() {
                return pkgdetails;
            }

            /**
             * Sets the value of the pkgdetails property.
             * 
             * @param value
             *     allowed object is
             *     {@link Gati.Details.Req.PKGDETAILS }
             *     
             */
            public void setPKGDETAILS(Gati.Details.Req.PKGDETAILS value) {
                this.pkgdetails = value;
            }

            /**
             * Gets the value of the receivermobileno property.
             * 
             */
            public long getRECEIVERMOBILENO() {
                return receivermobileno;
            }

            /**
             * Sets the value of the receivermobileno property.
             * 
             */
            public void setRECEIVERMOBILENO(long value) {
                this.receivermobileno = value;
            }

            /**
             * Gets the value of the custDateDelivey property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCustDateDelivey() {
                return custDateDelivey;
            }

            /**
             * Sets the value of the custDateDelivey property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCustDateDelivey(String value) {
                this.custDateDelivey = value;
            }

            /**
             * Gets the value of the splInstruction property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSPLInstruction() {
                return splInstruction;
            }

            /**
             * Sets the value of the splInstruction property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSPLInstruction(String value) {
                this.splInstruction = value;
            }

            /**
             * Gets the value of the prodservcode property.
             * 
             */
            public byte getPRODSERVCODE() {
                return prodservcode;
            }

            /**
             * Sets the value of the prodservcode property.
             * 
             */
            public void setPRODSERVCODE(byte value) {
                this.prodservcode = value;
            }

            /**
             * Gets the value of the custvendcode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCUSTVENDCODE() {
                return custvendcode;
            }

            /**
             * Sets the value of the custvendcode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCUSTVENDCODE(String value) {
                this.custvendcode = value;
            }

            /**
             * Gets the value of the goodsdesc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGOODSDESC() {
                return goodsdesc;
            }

            /**
             * Sets the value of the goodsdesc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGOODSDESC(String value) {
                this.goodsdesc = value;
            }

            /**
             * Gets the value of the orderquantity property.
             * 
             */
            public byte getORDERQUANTITY() {
                return orderquantity;
            }

            /**
             * Sets the value of the orderquantity property.
             * 
             */
            public void setORDERQUANTITY(byte value) {
                this.orderquantity = value;
            }

            /**
             * Gets the value of the sellername property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSELLERNAME() {
                return sellername;
            }

            /**
             * Sets the value of the sellername property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSELLERNAME(String value) {
                this.sellername = value;
            }

            /**
             * Gets the value of the selleradd1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSELLERADD1() {
                return selleradd1;
            }

            /**
             * Sets the value of the selleradd1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSELLERADD1(String value) {
                this.selleradd1 = value;
            }

            /**
             * Gets the value of the selleradd2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSELLERADD2() {
                return selleradd2;
            }

            /**
             * Sets the value of the selleradd2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSELLERADD2(String value) {
                this.selleradd2 = value;
            }

            /**
             * Gets the value of the selleradd3 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSELLERADD3() {
                return selleradd3;
            }

            /**
             * Sets the value of the selleradd3 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSELLERADD3(String value) {
                this.selleradd3 = value;
            }

            /**
             * Gets the value of the sellerdist property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSELLERDIST() {
                return sellerdist;
            }

            /**
             * Sets the value of the sellerdist property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSELLERDIST(String value) {
                this.sellerdist = value;
            }

            /**
             * Gets the value of the sellercity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSELLERCITY() {
                return sellercity;
            }

            /**
             * Sets the value of the sellercity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSELLERCITY(String value) {
                this.sellercity = value;
            }

            /**
             * Gets the value of the sellerpincode property.
             * 
             */
            public int getSELLERPINCODE() {
                return sellerpincode;
            }

            /**
             * Sets the value of the sellerpincode property.
             * 
             */
            public void setSELLERPINCODE(int value) {
                this.sellerpincode = value;
            }

            /**
             * Gets the value of the sellerstatecode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSELLERSTATECODE() {
                return sellerstatecode;
            }

            /**
             * Sets the value of the sellerstatecode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSELLERSTATECODE(String value) {
                this.sellerstatecode = value;
            }

            /**
             * Gets the value of the sellerphoneno property.
             * 
             */
            public long getSELLERPHONENO() {
                return sellerphoneno;
            }

            /**
             * Sets the value of the sellerphoneno property.
             * 
             */
            public void setSELLERPHONENO(long value) {
                this.sellerphoneno = value;
            }

            /**
             * Gets the value of the selleremail property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSELLEREMAIL() {
                return selleremail;
            }

            /**
             * Sets the value of the selleremail property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSELLEREMAIL(String value) {
                this.selleremail = value;
            }

            /**
             * Gets the value of the bookingbasis property.
             * 
             */
            public byte getBOOKINGBASIS() {
                return bookingbasis;
            }

            /**
             * Sets the value of the bookingbasis property.
             * 
             */
            public void setBOOKINGBASIS(byte value) {
                this.bookingbasis = value;
            }

            /**
             * Gets the value of the sellertinno property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSELLERTINNO() {
                return sellertinno;
            }

            /**
             * Sets the value of the sellertinno property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSELLERTINNO(String value) {
                this.sellertinno = value;
            }

            /**
             * Gets the value of the sellervatno property.
             * 
             */
            public short getSELLERVATNO() {
                return sellervatno;
            }

            /**
             * Sets the value of the sellervatno property.
             * 
             */
            public void setSELLERVATNO(short value) {
                this.sellervatno = value;
            }

            /**
             * Gets the value of the uom property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUOM() {
                return uom;
            }

            /**
             * Sets the value of the uom property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUOM(String value) {
                this.uom = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="PKG_INFO" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="PKG_NO" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                   &lt;element name="PKG_LN" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="PKG_BR" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="PKG_HT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="PKG_WT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "pkginfo"
            })
            public static class PKGDETAILS {

                @XmlElement(name = "PKG_INFO")
                protected List<Gati.Details.Req.PKGDETAILS.PKGINFO> pkginfo;

                /**
                 * Gets the value of the pkginfo property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the pkginfo property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getPKGINFO().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Gati.Details.Req.PKGDETAILS.PKGINFO }
                 * 
                 * 
                 */
                public List<Gati.Details.Req.PKGDETAILS.PKGINFO> getPKGINFO() {
                    if (pkginfo == null) {
                        pkginfo = new ArrayList<Gati.Details.Req.PKGDETAILS.PKGINFO>();
                    }
                    return this.pkginfo;
                }
                
                public void setPKGINFO(List<Gati.Details.Req.PKGDETAILS.PKGINFO> value) {
                    this.pkginfo = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="PKG_NO" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *         &lt;element name="PKG_LN" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="PKG_BR" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="PKG_HT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="PKG_WT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "pkgno",
                    "pkgln",
                    "pkgbr",
                    "pkght",
                    "pkgwt"
                })
                public static class PKGINFO {

                    @XmlElement(name = "PKG_NO")
                    protected int pkgno;
                    @XmlElement(name = "PKG_LN")
                    protected byte pkgln;
                    @XmlElement(name = "PKG_BR")
                    protected byte pkgbr;
                    @XmlElement(name = "PKG_HT")
                    protected byte pkght;
                    @XmlElement(name = "PKG_WT")
                    protected byte pkgwt;

                    /**
                     * Gets the value of the pkgno property.
                     * 
                     */
                    public int getPKGNO() {
                        return pkgno;
                    }

                    /**
                     * Sets the value of the pkgno property.
                     * 
                     */
                    public void setPKGNO(int value) {
                        this.pkgno = value;
                    }

                    /**
                     * Gets the value of the pkgln property.
                     * 
                     */
                    public byte getPKGLN() {
                        return pkgln;
                    }

                    /**
                     * Sets the value of the pkgln property.
                     * 
                     */
                    public void setPKGLN(byte value) {
                        this.pkgln = value;
                    }

                    /**
                     * Gets the value of the pkgbr property.
                     * 
                     */
                    public byte getPKGBR() {
                        return pkgbr;
                    }

                    /**
                     * Sets the value of the pkgbr property.
                     * 
                     */
                    public void setPKGBR(byte value) {
                        this.pkgbr = value;
                    }

                    /**
                     * Gets the value of the pkght property.
                     * 
                     */
                    public byte getPKGHT() {
                        return pkght;
                    }

                    /**
                     * Sets the value of the pkght property.
                     * 
                     */
                    public void setPKGHT(byte value) {
                        this.pkght = value;
                    }

                    /**
                     * Gets the value of the pkgwt property.
                     * 
                     */
                    public byte getPKGWT() {
                        return pkgwt;
                    }

                    /**
                     * Sets the value of the pkgwt property.
                     * 
                     */
                    public void setPKGWT(byte value) {
                        this.pkgwt = value;
                    }

                }

            }

        }

    }

}
